from datetime import datetime
from typing import Protocol, Optional
from ...domain import EventLogAgg


class IEventLogRepo(Protocol):
    async def get_by_id(self, source_id: str) -> Optional[EventLogAgg]: ...
    async def get_all(self) -> list[EventLogAgg]: ...
    async def get_all_active(self) -> list[EventLogAgg]: ...
    async def save(self, agg: EventLogAgg) -> None: ...
    async def delete(self, source_id: str) -> None: ...
    async def update_last_seen(self, source_id: str, timestamp: datetime) -> None: ...
