from typing import Protocol
from ...domain import EventDetectedEvent, SourceTimeoutEvent, SourceDiscoveredEvent, SourceDownEvent


class INotificationGateway(Protocol):
    async def send_event_detected(self, event: EventDetectedEvent) -> None: ...
    async def send_timeout_alert(self, event: SourceTimeoutEvent) -> None: ...
    async def send_source_discovered(self, event: SourceDiscoveredEvent) -> None: ...
    async def send_source_down(self, event: SourceDownEvent) -> None: ...
