from typing import Protocol, Optional
from notifications.domain import TelegramSubscriberEnt


class ISubscriberRepo(Protocol):
    async def get_all(self) -> list[TelegramSubscriberEnt]: ...
    async def get_active(self) -> list[TelegramSubscriberEnt]: ...
    async def get_active_for_events(self) -> list[TelegramSubscriberEnt]: ...
    async def get_active_for_timeouts(self) -> list[TelegramSubscriberEnt]: ...
    async def get_active_for_services(self) -> list[TelegramSubscriberEnt]: ...
    async def get_by_chat_id(self, chat_id: int) -> Optional[TelegramSubscriberEnt]: ...
    async def save(self, subscriber: TelegramSubscriberEnt) -> None: ...
